import { useState, type FormEvent } from 'react';
import { createRecord, uploadRecordImage, updateRecord } from '../../../api/recordsApi';
import type { RecordFormProps } from '../types';

export function RecordForm({ initial, language, onSaved, onCancel }: RecordFormProps) {
  const [title, setTitle] = useState(initial?.title || ''); const [contentId, setContentId] = useState(initial?.contentId || ''); const [visitedAt, setVisitedAt] = useState(initial?.visitedAt || new Date().toISOString().slice(0, 10)); const [memo, setMemo] = useState(initial?.memo || ''); const [imageUrl, setImageUrl] = useState(initial?.imageUrl || ''); const [saving, setSaving] = useState(false); const [uploading, setUploading] = useState(false); const [error, setError] = useState('');
  async function handleImage(file?: File) { if (!file) return; setUploading(true); setError(''); try { setImageUrl(await uploadRecordImage(file)); } catch (uploadError) { setError(uploadError instanceof Error ? uploadError.message : '이미지 업로드에 실패했습니다.'); } finally { setUploading(false); } }
  async function submit(event: FormEvent) { event.preventDefault(); if (!title.trim()) { setError('장소명 또는 제목을 입력해 주세요.'); return; } setSaving(true); setError(''); try { const input = { title: title.trim(), contentId: contentId.trim(), visitedAt, memo: memo.trim(), imageUrl, language }; onSaved(initial ? await updateRecord(initial.id, input) : await createRecord(input)); } catch (saveError) { setError(saveError instanceof Error ? saveError.message : '기록을 저장하지 못했습니다.'); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2"><label className="sm:col-span-2"><span className="label">장소명 또는 제목</span><input className="field" value={title} onChange={(event) => setTitle(event.target.value)} maxLength={200} required /></label><label><span className="label">방문 날짜</span><input className="field" type="date" value={visitedAt} onChange={(event) => setVisitedAt(event.target.value)} required /></label><label><span className="label">관광지 ID <em>(선택)</em></span><input className="field" value={contentId} onChange={(event) => setContentId(event.target.value)} placeholder="예: 126508" /></label><label className="sm:col-span-2"><span className="label">짧은 기록</span><textarea className="field min-h-32 resize-y" value={memo} onChange={(event) => setMemo(event.target.value)} maxLength={2000} /></label><label className="sm:col-span-2"><span className="label">대표 이미지</span><input className="block w-full text-sm text-slate-500" type="file" accept="image/png,image/jpeg,image/gif,image/webp" onChange={(event) => void handleImage(event.target.files?.[0])} />{uploading && <span className="mt-2 block text-xs text-suwon">이미지 업로드 중...</span>}{imageUrl && <img className="mt-3 h-28 w-full rounded-2xl object-cover" src={imageUrl} alt="업로드 미리보기" />}</label></div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-xl px-4 py-3 text-sm font-bold text-slate-500">취소</button><button type="submit" disabled={saving || uploading} className="rounded-xl bg-suwon px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving ? '저장 중...' : initial ? '기록 수정' : '기록 남기기'}</button></div></form>;
}
