import { useEffect, useState } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { deleteRecord, getRecord, type RecordLanguage, type TravelRecord } from '../api/recordsApi';
import { NaverMapFallback } from '../components/map/NaverMapFallback';
import { RecordForm } from '../features/records/components/RecordForm';
import { SpotLocationMap } from '../features/spots/components/SpotLocationMap';

const languages = new Set<RecordLanguage>(['kor', 'eng', 'jpn', 'chs', 'cht']);
export function RecordDetailPage() {
  const { id } = useParams(); const [params] = useSearchParams(); const rawLanguage = params.get('language') || 'kor'; const language = (languages.has(rawLanguage as RecordLanguage) ? rawLanguage : 'kor') as RecordLanguage; const [record, setRecord] = useState<TravelRecord>(); const [error, setError] = useState(''); const [editing, setEditing] = useState(false); const navigate = useNavigate();
  useEffect(() => { if (!id) return; void getRecord(Number(id), language).then(setRecord).catch((loadError) => setError(loadError instanceof Error ? loadError.message : '기록을 불러오지 못했습니다.')); }, [id, language]);
  if (error) return <section className="mx-auto max-w-3xl px-5 py-24 text-center"><NaverMapFallback message={error} tone="error" /><Link to="/records" className="mt-5 inline-block rounded-xl bg-suwon px-5 py-3 font-bold text-white">기록 목록으로</Link></section>;
  if (!record) return <section className="mx-auto max-w-3xl px-5 py-24"><div className="h-96 animate-pulse rounded-[2rem] bg-slate-200" /></section>;
  const currentRecord = record;
  async function remove() { if (!window.confirm('이 기록을 삭제할까요?')) return; await deleteRecord(currentRecord.id); navigate('/records'); }
  return <section className="mx-auto max-w-5xl px-5 py-12"><Link className="mb-8 inline-block text-sm font-bold text-suwon" to="/records">← 기록 목록</Link>{editing ? <RecordForm initial={record} language={language} onSaved={(saved) => { setRecord(saved); setEditing(false); }} onCancel={() => setEditing(false)} /> : <><div className="overflow-hidden rounded-[2rem] bg-white shadow-sm"><div className="relative h-72 bg-gradient-to-br from-blue-100 to-slate-200 md:h-[28rem]">{record.imageUrl && <img src={record.imageUrl} alt="" className="h-full w-full object-cover" />}<div className="absolute inset-0 bg-gradient-to-t from-slate-950/80 to-transparent" /><div className="absolute bottom-0 p-7 text-white"><p className="text-sm font-bold text-blue-200">{record.visitedAt}</p><h1 className="mt-2 text-4xl font-black">{record.title}</h1></div></div><div className="grid gap-8 p-7 md:grid-cols-[1fr_280px]"><article><p className="whitespace-pre-wrap text-lg leading-8 text-slate-700">{record.memo || '아직 글로 남긴 이야기가 없습니다.'}</p></article><aside className="space-y-3 text-sm text-slate-500"><p>📍 {record.location || '수원'}</p><div className="flex gap-2"><button type="button" onClick={() => setEditing(true)} className="rounded-xl bg-slate-100 px-4 py-2 font-bold text-slate-700">수정</button><button type="button" onClick={() => void remove()} className="rounded-xl bg-red-50 px-4 py-2 font-bold text-red-600">삭제</button></div></aside></div></div>{record.latitude != null && record.longitude != null && <div className="mt-8"><h2 className="mb-3 text-xl font-black">기억의 장소</h2><SpotLocationMap latitude={record.latitude} longitude={record.longitude} title={record.title} /></div>}</>}</section>;
}
